server:
  port: 9001
spring:
  application:
    name: itoken-gateway
  #分布式链路配置
  zipkin:
    base-url: http://112.126.59.115:9411
  sleuth:
    sampler:
      probability: 1


eureka:
  instance:
    hostname: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
