spring:
  application:
    name: itoken-registry

eureka:
  instance:
    hostname: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://112.126.59.115:7001/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"